apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: triall-prod-alfresco-alfresco-router
  labels:
    app: triall-prod-alfresco-alfresco-router
    chart: alfresco-content-services-triall-1.1.6
    release: triall-prod-alfresco
    heritage: Tiller
    component: transformrouter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: triall-prod-alfresco-alfresco-router
        release: triall-prod-alfresco
        component: transformrouter
    spec:
      imagePullSecrets:
        - name: quay-registry-secret
      containers:
      - envFrom:
        - configMapRef:
            name: triall-prod-alfresco-alfresco-router-configmap
        image: quay.io/alfresco/alfresco-transform-router:0.3.1-RC
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8095
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: alfresco-content-services-triall
        ports:
        - containerPort: 8095
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8095
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

