#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: triall-prod-alfresco-alfresco-cs-share
  labels:
    app: triall-prod-alfresco-alfresco-cs-share
    chart: alfresco-content-services-triall-1.1.6
    release: triall-prod-alfresco
    heritage: Tiller
    component: share
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: triall-prod-alfresco-alfresco-cs-share
        release: triall-prod-alfresco
        component: share
    spec:
      imagePullSecrets:
        - name: quay-registry-secret
      containers:
      - envFrom:
        - configMapRef:
            name: triall-prod-alfresco-alfresco-cs-share-configmap
        image: alfresco/alfresco-share:6.1.0-RC1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /share
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 130
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: alfresco-content-services-triall
        volumeMounts:
          - mountPath: /usr/local/tomcat/shared/classes/alfresco-global.properties
            name: global-properties-shared
            subPath: alfresco-global.properties
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /share
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            memory: 2000Mi
          requests:
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: triall-prod-alfresco-alfresco-cs-global-properties-shared
        name: global-properties-shared
