apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: triall-prod-alfresco-alfresco-router
    chart: alfresco-content-services-triall-1.1.6
    component: transformrouter
    heritage: Tiller
    release: triall-prod-alfresco
  name: triall-prod-alfresco-alfresco-router
  namespace: triall-prod
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: triall-prod-alfresco-alfresco-router
      component: transformrouter
      release: triall-prod-alfresco
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: triall-prod-alfresco-alfresco-router
        component: transformrouter
        release: triall-prod-alfresco
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: triall-prod-alfresco-alfresco-router-configmap
        image: quay.io/alfresco/alfresco-transform-router:0.3.1-RC
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8095
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: alfresco-content-services-triall
        ports:
        - containerPort: 8095
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8095
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
