apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-06-19T09:46:48Z"
  generation: 1
  labels:
    app: triall-prod-alfresco-alfresco-dw
    chart: alfresco-digital-workspace-1.0.0
    component: digitalWorkspaceApplication
    heritage: Tiller
    release: triall-prod-alfresco
  name: triall-prod-alfresco-alfresco-dw
  namespace: triall-prod
  resourceVersion: "13445161"
  selfLink: /apis/extensions/v1beta1/namespaces/triall-prod/deployments/triall-prod-alfresco-alfresco-dw
  uid: 287fa3f4-9277-11e9-98e6-06ce065d3256
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: triall-prod-alfresco-alfresco-dw
      component: digitalWorkspaceApplication
      release: triall-prod-alfresco
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: triall-prod-alfresco-alfresco-dw
        component: digitalWorkspaceApplication
        release: triall-prod-alfresco
    spec:
      containers:
      - env:
        - name: BASEPATH
          value: ./
        image: quay.io/alfresco/alfresco-digital-workspace:1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 130
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: alfresco-digital-workspace
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-19T09:46:49Z"
    lastUpdateTime: "2019-06-19T09:46:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
