apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-06-19T09:46:49Z"
  generation: 1
  labels:
    app: triall-prod-alfresco-alfresco-filestore
    chart: alfresco-content-services-triall-1.1.6
    component: transformers
    heritage: Tiller
    release: triall-prod-alfresco
  name: triall-prod-alfresco-alfresco-filestore
  namespace: triall-prod
  resourceVersion: "13446180"
  selfLink: /apis/extensions/v1beta1/namespaces/triall-prod/deployments/triall-prod-alfresco-alfresco-filestore
  uid: 288740a9-9277-11e9-98e6-06ce065d3256
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: triall-prod-alfresco-alfresco-filestore
      component: transformers
      release: triall-prod-alfresco
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: triall-prod-alfresco-alfresco-filestore
        component: transformers
        release: triall-prod-alfresco
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: triall-prod-alfresco-alfresco-filestore-configmap
        image: alfresco/alfresco-shared-file-store:0.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /live
            port: 8099
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: alfresco-content-services-triall
        ports:
        - containerPort: 8099
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8099
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/Alfresco
          name: data
          subPath: triall-prod/alfresco/acs/filestore
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: alfresco-volume-claim
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-19T09:46:50Z"
    lastUpdateTime: "2019-06-19T09:46:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
