apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
  name: triall-prod-alfresco-alfresco-cs-tika
    app: triall-prod-alfresco-alfresco-cs-tika
    chart: alfresco-content-services-triall-1.1.6
    release: triall-prod-alfresco
    heritage: Tiller
    component: transformers
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: triall-prod-alfresco-alfresco-cs-tika
        release: triall-prod-alfresco
        component: transformers
    spec:
      imagePullSecrets:
        - name: quay-registry-secret
      containers:
      - envFrom:
        - configMapRef:
            name: triall-prod-alfresco-alfresco-cs-tika-configmap
        image: quay.io/alfresco/alfresco-tika:2.0.6-RC
        imagePullPolicy: Always
        name: alfresco-content-services-triall
        ports:
        - containerPort: 8090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /live
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
