apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-06-19T09:46:49Z"
  generation: 1
  labels:
    app: triall-prod-alfresco-alfresco-router
    chart: alfresco-content-services-triall-1.1.6
    component: transformrouter
    heritage: Tiller
    release: triall-prod-alfresco
  name: triall-prod-alfresco-alfresco-router
  namespace: triall-prod
  resourceVersion: "13445262"
  selfLink: /apis/extensions/v1beta1/namespaces/triall-prod/deployments/triall-prod-alfresco-alfresco-router
  uid: 28916926-9277-11e9-98e6-06ce065d3256
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: triall-prod-alfresco-alfresco-router
      component: transformrouter
      release: triall-prod-alfresco
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: triall-prod-alfresco-alfresco-router
        component: transformrouter
        release: triall-prod-alfresco
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: triall-prod-alfresco-alfresco-router-configmap
        image: quay.io/alfresco/alfresco-transform-router:0.3.1-RC
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8095
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: alfresco-content-services-triall
        ports:
        - containerPort: 8095
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8095
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-19T09:46:50Z"
    lastUpdateTime: "2019-06-19T09:46:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
