# Defines the deployment for the alfresco share app
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "content-services.shortname" . }}-share
  labels:
    app: {{ template "content-services.shortname" . }}-share
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: share
spec:
  replicas: {{ .Values.share.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "content-services.shortname" . }}-share
        release: {{ .Release.Name }}
        component: share
    spec:
      {{- if .Values.registryPullSecrets }}
      # only set this secret if a private docker registry variable is defined
      imagePullSecrets:
        - name: {{ .Values.registryPullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.share.image.repository }}:{{ .Values.share.image.tag }}"
          imagePullPolicy: {{ .Values.share.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.share.image.internalPort }}
          resources:
{{ toYaml .Values.share.resources | indent 12 }}
          envFrom:
          - configMapRef:
              name: {{ template "content-services.shortname" . }}-share-configmap
          volumeMounts:
          - name: global-properties-shared
            mountPath: /usr/local/tomcat/shared/classes/alfresco-global.properties
            subPath: alfresco-global.properties
          readinessProbe:
            httpGet:
              path: /share
              port: {{ .Values.share.image.internalPort }}
            initialDelaySeconds: {{ .Values.share.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.share.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.share.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /share
              port: {{ .Values.share.image.internalPort }}
            initialDelaySeconds: {{ .Values.share.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.share.livenessProbe.periodSeconds }}
            failureThreshold: 1
            timeoutSeconds: {{ .Values.share.livenessProbe.timeoutSeconds }}
      volumes:
      - name: global-properties-shared
        configMap:
          name: {{ template "content-services.shortname" . }}-global-properties-shared
