#
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: triall-prod-alfresco-alfresco-filestore
  labels:
    app: triall-prod-alfresco-alfresco-filestore
    chart: alfresco-content-services-triall-1.1.6
    release: triall-prod-alfresco
    heritage: Tiller
    component: transformers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: triall-prod-alfresco-alfresco-filestore
        release: triall-prod-alfresco
        component: transformers
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: triall-prod-alfresco-alfresco-filestore-configmap
        image: alfresco/alfresco-shared-file-store:0.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /live
            port: 8099
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: alfresco-content-services-triall
        ports:
        - containerPort: 8099
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8099
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/Alfresco
          name: data
          subPath: triall-prod/alfresco/acs/filestore
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: alfresco-volume-claim
