apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: alfresco-adf-demo
  annotations:
    ingress.kubernetes.io/ssl-redirect: {{ .Values.repository.ingress.sslRedirect | quote }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.repository.ingress.sslRedirect | quote }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ ^(/.*/proxy/alfresco/api/solr/.*)$ {return 403 ;}
                  location ~ ^(/.*/-default-/proxy/alfresco/api/.*)$ {return 403;}
    nginx.ingress.kubernetes.io/proxy-body-size: 5g
spec:
  rules:
  - host: {{ .Values.externalHost }}
    http:
      paths:
      - path: /
        backend:
          serviceName: alfresco-adf-demo
          servicePort: 80

