apiVersion: v1
kind: Service
metadata:
  name: triall-agent
  annotations:
    api.service.kubernetes.io/path: /
spec:
  type: ClusterIP
  ports:
  - port: 22240
    protocol: TCP
    targetPort: 22240
    name: ms-http
  selector:
    app: triall-agent